#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift(File.expand_path('../lib', __dir__))
require 'flgen'

begin
  FLGen::CLI.new.run(ARGV)
rescue FLGen::FLGenError => e
  abort e.to_s
end
