#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift(File.expand_path('../lib', __dir__))
require 'file_list_generator'

begin
  FLGen::CLI.new.run(ARGV)
rescue FLGen::FileListGeneratorError => e
  abort e.to_s
end
