name: CI

on: [push, pull_request]

jobs:
  rspec:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: ['3.1', '3.0']

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run RSpec
        run: |
          bundle exec rake rspec
