name: CI

on: [push, pull_request]

jobs:
  rspec:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: ['3.4', '3.3', '3.2', '3.1']
    env:
      BUNDLE_WITH: 'development_common development_test'
      BUNDLE_WITHOUT: 'development_lint development_local'

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run RSpec
        run: |
          bundle exec rake coverage

      - name: Upload coverage report
        uses: codecov/codecov-action@v5
        with:
          name: ${{ matrix.ruby  }}
          files: ./coverage/coverage.xml
          fail_ci_if_error: false
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
